dope ass home screen
wyncode/C38_just_play pull request #33
Opened 2020-09-04 00:28 UTC by zteching

update

2020-09-04 02:32 UTC, leopolicastro approved these changes

2020-09-04 13:40 UTC, naaltunian commented
let's avoid commit messages like "dope ass". Doesn't look professional. Also there's a conflict in Home.jsx.

2020-09-06 15:46 UTC, Stommy123 commented on package.json
> +    "node-sass": "^4.14.1",
I don't see sass being used anywhere in this codebase. Could we please remove this dependency?

2020-09-06 15:47 UTC, Stommy123 requested changes
Looks good! Small comment about an unused dependency

2020-09-06 23:10 UTC, naaltunian commented
lots of conflicts :/

2020-09-15 12:50 UTC, closed without merging